version: "3.8"

services:
  db:
    container_name: rest_app_db
    build: ./postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - rest-app

  admin:
    container_name: rest_app_db_adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080
    networks:
      - rest-app

  backend:
    container_name: backend
    build: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8888
    networks:
      - rest-app

networks:
  rest-app:
